export const employeesList = [
  {
    employeeId: "0001",
    name: "John Doe",
    email: "john.doe@example.com",
    joiningDate: "2025-08-23",
    department: "Engineering",
    role: "Software Engineer",
    status: "Active",
  },
  {
    employeeId: "0002",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    joiningDate: "2024-07-15",
    department: "Marketing",
    role: "Marketing Manager",
    status: "Active",
  },
  {
    employeeId: "0003",
    name: "Robert Brown",
    email: "robert.brown@example.com",
    joiningDate: "2023-06-10",
    department: "Sales",
    role: "Sales Executive",
    status: "Inactive",
  },
  {
    employeeId: "0004",
    name: "Emily Davis",
    email: "emily.davis@example.com",
    joiningDate: "2025-01-12",
    department: "HR",
    role: "HR Manager",
    status: "Active",
  },
  {
    employeeId: "0005",
    name: "Michael Johnson",
    email: "michael.johnson@example.com",
    joiningDate: "2024-03-08",
    department: "Finance",
    role: "Financial Analyst",
    status: "Active",
  },
  {
    employeeId: "0006",
    name: "Sarah Wilson",
    email: "sarah.wilson@example.com",
    joiningDate: "2025-02-20",
    department: "Engineering",
    role: "Frontend Developer",
    status: "Active",
  },
  {
    employeeId: "0007",
    name: "David Martinez",
    email: "david.martinez@example.com",
    joiningDate: "2023-12-05",
    department: "Engineering",
    role: "Backend Developer",
    status: "Inactive",
  },
  {
    employeeId: "0008",
    name: "Olivia Garcia",
    email: "olivia.garcia@example.com",
    joiningDate: "2024-09-18",
    department: "Marketing",
    role: "Content Writer",
    status: "Active",
  },
  {
    employeeId: "0009",
    name: "Daniel Lee",
    email: "daniel.lee@example.com",
    joiningDate: "2025-04-11",
    department: "Sales",
    role: "Account Manager",
    status: "Active",
  },
  {
    employeeId: "0010",
    name: "Sophia Hernandez",
    email: "sophia.hernandez@example.com",
    joiningDate: "2024-08-22",
    department: "HR",
    role: "Recruiter",
    status: "Inactive",
  },
  {
    employeeId: "0011",
    name: "James Clark",
    email: "james.clark@example.com",
    joiningDate: "2023-11-30",
    department: "Engineering",
    role: "DevOps Engineer",
    status: "Active",
  },
  {
    employeeId: "0012",
    name: "Mia Lewis",
    email: "mia.lewis@example.com",
    joiningDate: "2025-05-14",
    department: "Finance",
    role: "Accountant",
    status: "Active",
  },
  {
    employeeId: "0013",
    name: "William Walker",
    email: "william.walker@example.com",
    joiningDate: "2024-10-01",
    department: "Sales",
    role: "Sales Manager",
    status: "Active",
  },
  {
    employeeId: "0014",
    name: "Ava Hall",
    email: "ava.hall@example.com",
    joiningDate: "2025-03-05",
    department: "Marketing",
    role: "SEO Specialist",
    status: "Active",
  },
  {
    employeeId: "0015",
    name: "Alexander Allen",
    email: "alexander.allen@example.com",
    joiningDate: "2023-07-19",
    department: "Engineering",
    role: "Full Stack Developer",
    status: "Inactive",
  },
  {
    employeeId: "0016",
    name: "Isabella Young",
    email: "isabella.young@example.com",
    joiningDate: "2024-06-24",
    department: "HR",
    role: "HR Executive",
    status: "Active",
  },
  {
    employeeId: "0017",
    name: "Matthew King",
    email: "matthew.king@example.com",
    joiningDate: "2025-01-30",
    department: "Finance",
    role: "Financial Analyst",
    status: "Active",
  },
  {
    employeeId: "0018",
    name: "Charlotte Wright",
    email: "charlotte.wright@example.com",
    joiningDate: "2024-09-12",
    department: "Marketing",
    role: "Brand Manager",
    status: "Active",
  },
  {
    employeeId: "0019",
    name: "Benjamin Scott",
    email: "benjamin.scott@example.com",
    joiningDate: "2025-02-17",
    department: "Engineering",
    role: "QA Engineer",
    status: "Active",
  },
  {
    employeeId: "0020",
    name: "Amelia Adams",
    email: "amelia.adams@example.com",
    joiningDate: "2023-08-28",
    department: "Sales",
    role: "Sales Executive",
    status: "Inactive",
  },
];

export const getEmployees = async () => {
  try {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve(employeesList);
      }, 2000);
    });
  } catch (error) {
    console.error(error);
    return [];
  }
};
