export const departmentList = [
  { label: "Engineering", value: "Engineering" },
  { label: "Marketing", value: "Marketing" },
  { label: "Sales", value: "Sales" },
  { label: "HR", value: "HR" },
  { label: "Finance", value: "Finance" },
];
export const rolesList = [
  { label: "Software Engineer", value: "Software Engineer" },
  { label: "Marketing Manager", value: "Marketing Manager" },
  { label: "Sales Executive", value: "Sales Executive" },
  { label: "HR Manager", value: "HR Manager" },
  { label: "Finance Analyst", value: "Finance Analyst" },
  { label: "Recruiter", value: "Recruiter" },
  { label: "QA Engineer", value: "QA Engineer" },
  { label: "FullStack Developer", value: "FullStack Developer" },
  { label: "SEO Specialist", value: "SEO Specialist" },
  { label: "HR Executive", value: "HR Executive" },
  { label: "Financial Analyst", value: "Financial Analyst" },
  { label: "Content Writer", value: "Content Writer" },
  { label: "Frontend Developer", value: "Frontend Developer" },
  { label: "Backend Developer", value: "Backend Developer" },
  { label: "DevOps Engineer", value: "DevOps Engineer" },
  { label: "Brand Manager", value: "Brand Manager" },
];
